spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false